Demonstrate how missing a dependency can cause confounding errors.
error: emit-module command failed with exit code 1 (use -v to see invocation)
[6/8] Emitting module TestUtils
<unknown>:0: error: missing required module 'llvmc'
[7/8] Compiling TestUtils Demo.swift
<unknown>:0: error: missing required module 'llvmc'
error: fatalError