Straighten out deployment targets.
CMake builds were failing due to:

  /Users/runner/work/hylo/hylo/hylo/Sources/FrontEnd/TypeChecking/Rewriting/RequirementTerm.swift:38:19: error: 'replacing(_:with:maxReplacements:)' is only available in macOS 13.0 or newer
  2024-06-20T14:11:52.0539460Z     .init(symbols.replacing(s.symbols, with: t.symbols))
  2024-06-20T14:11:52.0540230Z                   ^

SPM builds were failing due to the fact that deployment target was
.v14 while the CI runner was only macOS-13

These things need to be kept in sync.